storage: local

local:
  normalized_path: "tests/data/normalized"
  clustered_path: "tests/data/clustered"
  raw_path: "tests/data/raw"

cache:
  enabled: false

server:
  host: "127.0.0.1"
  port: 8000
